# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.2.0
      hooks:
        - id: trailing-whitespace
        - id: end-of-file-fixer
        - id: check-yaml
        - id: check-added-large-files
    - repo: https://github.com/psf/black
      rev: 25.1.0
      hooks:
        - id: black
          types: [python]
    - repo: local
      hooks:
        - id: black
          name: black
          entry: poetry -P python/bellechasse/ run black
          language: system
          types: [python]
        - id: pylint
          name: pylint
          entry: poetry -P python/bellechasse/ run pylint --rcfile=./python/bellechasse/pylintrc -f colorized ./python/bellechasse/
          require_serial: true
          language: system
          types: [python]
        # - id: mypy
        #   name: mypy
        #   entry: poetry -P python/bellechasse/ run mypy ./python/bellechasse/
        #   language: python
        #   types: [python]
        # - id: pytest
        #   name: pytest
        #   entry: poetry -P python/bellechasse/ run pytest ./python/bellechasse/
        #   language: python
        #   types: [python]
